// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtsPRF3LpBHxSJ86y6jwJDIdfxBsGdeJ0',
    appId: '1:657425286496:web:6f96ca895db0f1bf9cca05',
    messagingSenderId: '657425286496',
    projectId: 'cinepasse-51665',
    authDomain: 'cinepasse-51665.firebaseapp.com',
    storageBucket: 'cinepasse-51665.firebasestorage.app',
    measurementId: 'G-4W5QB205TQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNcYwyemEZeudXGfR_OWA32v01JTXKWnE',
    appId: '1:657425286496:android:015e104f2ca9f8419cca05',
    messagingSenderId: '657425286496',
    projectId: 'cinepasse-51665',
    storageBucket: 'cinepasse-51665.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDKLY6f606-wvD_LoqXTyPtBAeOAt0YWM',
    appId: '1:657425286496:ios:00f01e75d76345da9cca05',
    messagingSenderId: '657425286496',
    projectId: 'cinepasse-51665',
    storageBucket: 'cinepasse-51665.firebasestorage.app',
    iosBundleId: 'com.example.cinePasseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDKLY6f606-wvD_LoqXTyPtBAeOAt0YWM',
    appId: '1:657425286496:ios:00f01e75d76345da9cca05',
    messagingSenderId: '657425286496',
    projectId: 'cinepasse-51665',
    storageBucket: 'cinepasse-51665.firebasestorage.app',
    iosBundleId: 'com.example.cinePasseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtsPRF3LpBHxSJ86y6jwJDIdfxBsGdeJ0',
    appId: '1:657425286496:web:f7fe7f8b8ce7171e9cca05',
    messagingSenderId: '657425286496',
    projectId: 'cinepasse-51665',
    authDomain: 'cinepasse-51665.firebaseapp.com',
    storageBucket: 'cinepasse-51665.firebasestorage.app',
    measurementId: 'G-696TDKZ0Q8',
  );
}
